
all:
	        ~/.platformio/penv/bin/platformio -f -c vim run

upload:
	        ~/.platformio/penv/bin/platformio -f -c vim run --target upload

clean:
	        ~/.platformio/penv/bin/platformio -f -c vim run --target clean

program:
	        ~/.platformio/penv/bin/platformio -f -c vim run --target program

uploadfs:
	        ~/.platformio/penv/bin/platformio -f -c vim run --target uploadfs

update:
	        ~/.platformio/penv/bin/platformio -f -c vim update
